import Foundation
import SwiftData

/// One extracted figure's seed data -- produced by `tools/extract_figures.py` +
/// `tools/caption_figures.py` (image extraction + chapter-mapping is free/local; captioning is
/// the one paid step, run once against Rajan's own Anthropic key). Mirrors `SeedLoader`'s
/// JSON-document pattern for the same reason: this data is authored/regenerated by a script,
/// not hand-written, so it belongs in a bundled JSON resource rather than a Swift literal.
struct SeedFigureDocument: Codable {
    let fileName: String
    let page: Int
    let book: String
    let chapter: String
    let caption: String
}

enum FigureSeedLoader {
    /// Loads `Resources/Figures/figures_manifest.json` (if bundled) and upserts each entry,
    /// matched to its `Book`/`Chapter` by title. Safe to call on every launch: an entry whose
    /// `fileName` already has a `Figure` row is skipped, so this never duplicates. A book or
    /// chapter that isn't seeded yet (e.g. this runs before `SeedLoader` for some reason, or a
    /// figure's book/chapter title drifted from what's currently seeded) is skipped for that
    /// entry rather than crashing or inserting an orphaned `Figure` -- `FigureImageLoader`
    /// already tolerates a missing bundled image the same way, so a mismatch here just means
    /// that one figure doesn't show up, not a launch-time failure.
    static func seedBundledFigures(modelContext: ModelContext) {
        guard let url = Bundle.main.url(forResource: "figures_manifest", withExtension: "json", subdirectory: "Figures") else {
            return
        }
        guard let data = try? Data(contentsOf: url),
              let docs = try? JSONDecoder().decode([SeedFigureDocument].self, from: data) else {
            #if DEBUG
            print("FigureSeedLoader: failed to decode figures_manifest.json")
            #endif
            return
        }

        let existingFileNames = Set(((try? modelContext.fetch(FetchDescriptor<Figure>())) ?? []).map(\.fileName))
        var booksByTitle: [String: Book] = [:]
        for book in (try? modelContext.fetch(FetchDescriptor<Book>())) ?? [] {
            booksByTitle[book.title] = book
        }

        var inserted = 0
        for doc in docs where !existingFileNames.contains(doc.fileName) {
            guard let book = booksByTitle[doc.book] else { continue }
            guard let chapter = book.chapters.first(where: { $0.title == doc.chapter }) else { continue }
            let figure = Figure(fileName: doc.fileName, page: doc.page, caption: doc.caption, book: book, chapter: chapter)
            modelContext.insert(figure)
            inserted += 1
        }

        #if DEBUG
        if inserted > 0 {
            print("FigureSeedLoader: seeded \(inserted) figures")
        }
        #endif
    }
}
